// Generated by tools/generate_hyphenation.py from hyph-utf8. Do not hand-edit.
package io.github.yuroyami.kitepdf.core.text.hyphen

/**
 * Hyphenation patterns for Tamil, from the hyph-utf8 project
 * (https://github.com/hyphenation/tex-hyphen, commit 5684c0f51c0b81133db2efbe60a408b4155a3ff5,
 * hyph-utf8/tex/generic/hyph-utf8/patterns/txt/hyph-ta.pat.txt).
 *
 * Copyright (C) 2016 Santhosh Thottingal.
 *
 * Licence: This file is available under any of the following licences:
 *
 * MIT (https://opensource.org/licenses/MIT).
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and
 * associated documentation files (the "Software"), to deal in the Software without restriction,
 * including without limitation the rights to use, copy, modify, merge, publish, distribute,
 * sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all copies or
 * substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT
 * NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
 * DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 *
 * LGPL 3 or later (http://www.gnu.org/licenses/lgpl.html).
 *
 * GPL 3 or later (http://www.gnu.org/licenses/gpl.html).
 *
 * The patterns and exceptions are carried unmodified; only their packing into Kotlin strings is
 * new. One Knuth-Liang pattern, or one hyphenated exception word, per line. Generated by
 * tools/generate_hyphenation.py; do not edit by hand.
 */
internal object HyphTa : HyphenPatterns {
    override val minPrefix: Int get() = 1
    override val minSuffix: Int get() = 1

    override val patterns: String get() = P0
    override val exceptions: String get() = ""

    private const val P0 = """
2‍2
1‌1
1அ1
1ஆ1
1இ1
1ஈ1
1உ1
1ஊ1
1எ1
1ஏ1
1ஐ1
1ஒ1
1ஓ1
1ஔ1
ா1
ி1
ீ1
ு1
ூ1
ெ1
ே1
ை1
ொ1
ோ1
ௌ1
1க
1ங
1ச
1ஜ
1ஞ
1ட
1ண
1த
1ந
1ப
1ம
1ய
1ர
1ற
1ல
1ள
1ழ
1வ
1ஷ
1ஸ
1ஹ
2க்1
2ங்1
2ச்1
2ஞ்1
2ட்1
2ண்1
2த்1
2ன்1
2ந்1
2ப்1
2ம்1
2ய்1
2ர்1
2ற்1
2ல்1
2ள்1
2ழ்1
2வ்1
2ஷ்1
2ஸ்1
2ஹ்1
2ஂ1
2ஃ1
2ௗ1
2்1"""
}
