// Generated by tools/generate_hyphenation.py from hyph-utf8. Do not hand-edit.
package io.github.yuroyami.kitepdf.core.text.hyphen

/**
 * Hyphenation patterns for Hindi, from the hyph-utf8 project
 * (https://github.com/hyphenation/tex-hyphen, commit 5684c0f51c0b81133db2efbe60a408b4155a3ff5,
 * hyph-utf8/tex/generic/hyph-utf8/patterns/txt/hyph-hi.pat.txt).
 *
 * Copyright (C) 2016 Santhosh Thottingal.
 *
 * Licence: This file is available under any of the following licences:
 *
 * MIT (https://opensource.org/licenses/MIT).
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and
 * associated documentation files (the "Software"), to deal in the Software without restriction,
 * including without limitation the rights to use, copy, modify, merge, publish, distribute,
 * sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all copies or
 * substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT
 * NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
 * DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 *
 * LGPL 3 or later (http://www.gnu.org/licenses/lgpl.html).
 *
 * GPL 3 or later (http://www.gnu.org/licenses/gpl.html).
 *
 * The patterns and exceptions are carried unmodified; only their packing into Kotlin strings is
 * new. One Knuth-Liang pattern, or one hyphenated exception word, per line. Generated by
 * tools/generate_hyphenation.py; do not edit by hand.
 */
internal object HyphHi : HyphenPatterns {
    override val minPrefix: Int get() = 1
    override val minSuffix: Int get() = 1

    override val patterns: String get() = P0
    override val exceptions: String get() = ""

    private const val P0 = """
2‍2
1‌1
अ1
आ1
इ1
ई1
उ1
ऊ1
ऋ1
ॠ1
ऌ1
ॡ1
ए1
ऐ1
ओ1
औ1
ा1
ि1
ी1
ु1
ू1
ृ1
ॄ1
ॢ1
ॣ1
े1
ै1
ो1
ौ1
1क
1ख
1ग
1घ
1ङ
1च
1छ
1ज
1झ
1ञ
1ट
1ठ
1ड
1ढ
1ण
1त
1थ
1द
1ध
1न
1प
1फ
1ब
1भ
1म
1य
1र
1ल
1ळ
1व
1श
1ष
1स
1ह
2ँ1
2ं1
2ः1
2ऽ1
2॑1
2॒1
2्2"""
}
