// Generated by tools/generate_hyphenation.py from hyph-utf8. Do not hand-edit.
package io.github.yuroyami.kitepdf.core.text.hyphen

/**
 * One hyphenation pattern set of the hyph-utf8 project
 * (https://github.com/hyphenation/tex-hyphen, commit 5684c0f51c0b81133db2efbe60a408b4155a3ff5).
 */
internal interface HyphenPatterns {
    /** TeX's `lefthyphenmin`: the fewest characters a break leaves before it. */
    val minPrefix: Int

    /** TeX's `righthyphenmin`: the fewest characters a break leaves after it. */
    val minSuffix: Int

    /** The Knuth-Liang patterns, one to a line. */
    val patterns: String

    /** The exception words, one to a line with a hyphen at each break; empty when the set has none. */
    val exceptions: String
}

/** Every bundled set, by the name hyph-utf8 gives its files (`hyph-<name>.pat.txt`). */
internal object HyphenPatternSets {
    /** The name of every bundled set. */
    val ids: List<String> = listOf(
        "af", "as", "be", "bg", "bn", "ca", "cop", "cu",
        "cy", "da", "de-1901", "de-1996", "de-ch-1901", "el-monoton", "el-polyton", "en-gb",
        "en-us", "eo", "es", "et", "eu", "fi", "fi-x-school", "fr",
        "fur", "ga", "gl", "grc", "gu", "hi", "hr", "hsb",
        "hu", "ia", "is", "it", "ka", "kk", "kmr", "kn",
        "la", "la-x-classic", "la-x-liturgic", "lt", "ml", "mn-cyrl", "mr", "nb",
        "nl", "oc", "or", "pa", "pi", "pl", "pms", "pt",
        "rm", "ru", "sa", "sh-cyrl", "sh-latn", "sk", "sl", "sq",
        "sv", "ta", "te", "tk", "tr", "uk", "zh-latn-pinyin",
    )

    /** The set named [id], or null when none is bundled. Only that set's strings load. */
    fun byId(id: String): HyphenPatterns? = when (id) {
        "af" -> HyphAf
        "as" -> HyphAs
        "be" -> HyphBe
        "bg" -> HyphBg
        "bn" -> HyphBn
        "ca" -> HyphCa
        "cop" -> HyphCop
        "cu" -> HyphCu
        "cy" -> HyphCy
        "da" -> HyphDa
        "de-1901" -> HyphDe1901
        "de-1996" -> HyphDe1996
        "de-ch-1901" -> HyphDeCh1901
        "el-monoton" -> HyphElMonoton
        "el-polyton" -> HyphElPolyton
        "en-gb" -> HyphEnGb
        "en-us" -> HyphEnUs
        "eo" -> HyphEo
        "es" -> HyphEs
        "et" -> HyphEt
        "eu" -> HyphEu
        "fi" -> HyphFi
        "fi-x-school" -> HyphFiXSchool
        "fr" -> HyphFr
        "fur" -> HyphFur
        "ga" -> HyphGa
        "gl" -> HyphGl
        "grc" -> HyphGrc
        "gu" -> HyphGu
        "hi" -> HyphHi
        "hr" -> HyphHr
        "hsb" -> HyphHsb
        "hu" -> HyphHu
        "ia" -> HyphIa
        "is" -> HyphIs
        "it" -> HyphIt
        "ka" -> HyphKa
        "kk" -> HyphKk
        "kmr" -> HyphKmr
        "kn" -> HyphKn
        "la" -> HyphLa
        "la-x-classic" -> HyphLaXClassic
        "la-x-liturgic" -> HyphLaXLiturgic
        "lt" -> HyphLt
        "ml" -> HyphMl
        "mn-cyrl" -> HyphMnCyrl
        "mr" -> HyphMr
        "nb" -> HyphNb
        "nl" -> HyphNl
        "oc" -> HyphOc
        "or" -> HyphOr
        "pa" -> HyphPa
        "pi" -> HyphPi
        "pl" -> HyphPl
        "pms" -> HyphPms
        "pt" -> HyphPt
        "rm" -> HyphRm
        "ru" -> HyphRu
        "sa" -> HyphSa
        "sh-cyrl" -> HyphShCyrl
        "sh-latn" -> HyphShLatn
        "sk" -> HyphSk
        "sl" -> HyphSl
        "sq" -> HyphSq
        "sv" -> HyphSv
        "ta" -> HyphTa
        "te" -> HyphTe
        "tk" -> HyphTk
        "tr" -> HyphTr
        "uk" -> HyphUk
        "zh-latn-pinyin" -> HyphZhLatnPinyin
        else -> null
    }
}
