// Generated by tools/generate_hyphenation.py from hyph-utf8. Do not hand-edit.
package io.github.yuroyami.kitepdf.core.text.hyphen

/**
 * Hyphenation patterns for Malayalam, from the hyph-utf8 project
 * (https://github.com/hyphenation/tex-hyphen, commit 5684c0f51c0b81133db2efbe60a408b4155a3ff5,
 * hyph-utf8/tex/generic/hyph-utf8/patterns/txt/hyph-ml.pat.txt).
 *
 * Copyright (C) 2016 Santhosh Thottingal.
 *
 * Licence: This file is available under any of the following licences:
 *
 * MIT (https://opensource.org/licenses/MIT).
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and
 * associated documentation files (the "Software"), to deal in the Software without restriction,
 * including without limitation the rights to use, copy, modify, merge, publish, distribute,
 * sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all copies or
 * substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT
 * NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
 * DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 *
 * LGPL 3 or later (http://www.gnu.org/licenses/lgpl.html).
 *
 * GPL 3 or later (http://www.gnu.org/licenses/gpl.html).
 *
 * The patterns and exceptions are carried unmodified; only their packing into Kotlin strings is
 * new. One Knuth-Liang pattern, or one hyphenated exception word, per line. Generated by
 * tools/generate_hyphenation.py; do not edit by hand.
 */
internal object HyphMl : HyphenPatterns {
    override val minPrefix: Int get() = 1
    override val minSuffix: Int get() = 1

    override val patterns: String get() = P0
    override val exceptions: String get() = ""

    private const val P0 = """
2‍2
1‌1
1അ1
1ആ1
1ഇ1
1ഈ1
1ഉ1
1ഊ1
1ഋ1
1ൠ1
1ഌ1
1ൡ1
1എ1
1ഏ1
1ഐ1
1ഒ1
1ഓ1
1ഔ1
ാ1
ി1
ീ1
ു1
ൂ1
ൃ1
െ1
േ1
ൈ1
ൊ1
ോ1
ൌ1
ൗ1
1ക
1ഖ
1ഗ
1ഘ
1ങ
1ച
1ഛ
1ജ
1ഝ
1ഞ
1ട
1ഠ
1ഡ
1ഢ
1ണ
1ത
1ഥ
1ദ
1ധ
1ന
1പ
1ഫ
1ബ
1ഭ
1മ
1യ
1ര
1റ
1ല
1ള
1ഴ
1വ
1ശ
1ഷ
1സ
1ഹ
2ഃ1
2ം1
2്2
ന്2
ര്2
ള്2
ല്2
ക്2
ണ്2
2ന്‍
2ല്‍
2ള്‍
2ണ്‍
2ര്‍
2ക്‍
2ൺ
2ൻ
2ർ
2ൽ
2ൾ
2ൿ"""
}
