// Generated by tools/generate_hyphenation.py from hyph-utf8. Do not hand-edit.
package io.github.yuroyami.kitepdf.core.text.hyphen

/**
 * Hyphenation patterns for Kannada, from the hyph-utf8 project
 * (https://github.com/hyphenation/tex-hyphen, commit 5684c0f51c0b81133db2efbe60a408b4155a3ff5,
 * hyph-utf8/tex/generic/hyph-utf8/patterns/txt/hyph-kn.pat.txt).
 *
 * Copyright (C) 2016 Santhosh Thottingal.
 *
 * Licence: This file is available under any of the following licences:
 *
 * MIT (https://opensource.org/licenses/MIT).
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and
 * associated documentation files (the "Software"), to deal in the Software without restriction,
 * including without limitation the rights to use, copy, modify, merge, publish, distribute,
 * sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all copies or
 * substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT
 * NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
 * DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 *
 * LGPL 3 or later (http://www.gnu.org/licenses/lgpl.html).
 *
 * GPL 3 or later (http://www.gnu.org/licenses/gpl.html).
 *
 * The patterns and exceptions are carried unmodified; only their packing into Kotlin strings is
 * new. One Knuth-Liang pattern, or one hyphenated exception word, per line. Generated by
 * tools/generate_hyphenation.py; do not edit by hand.
 */
internal object HyphKn : HyphenPatterns {
    override val minPrefix: Int get() = 1
    override val minSuffix: Int get() = 1

    override val patterns: String get() = P0
    override val exceptions: String get() = ""

    private const val P0 = """
2‍2
1‌1
ಅ1
ಆ1
ಇ1
ಈ1
ಉ1
ಊ1
ಋ1
ೠ1
ಌ1
ೡ1
ಎ1
ಏ1
ಐ1
ಒ1
ಓ1
ಔ1
ಾ1
ಿ1
ೀ1
ು1
ೂ1
ೃ1
ೄ1
ೆ1
ೇ1
ೈ1
ೊ1
ೋ1
ೌ1
1ಕ
1ಖ
1ಗ
1ಘ
1ಙ
1ಚ
1ಛ
1ಜ
1ಝ
1ಞ
1ಟ
1ಠ
1ಡ
1ಢ
1ಣ
1ತ
1ಥ
1ದ
1ಧ
1ನ
1ಪ
1ಫ
1ಬ
1ಭ
1ಮ
1ಯ
1ರ
1ಱ
1ಲ
1ಳ
1ೞ
1ವ
1ಶ
1ಷ
1ಸ
1ಹ
2ಂ1
2ಃ1
2ಽ1
2ೕ1
2ೖ1
2್2"""
}
