// Generated by tools/generate_hyphenation.py from hyph-utf8. Do not hand-edit.
package io.github.yuroyami.kitepdf.core.text.hyphen

/**
 * Hyphenation patterns for Assamese, from the hyph-utf8 project
 * (https://github.com/hyphenation/tex-hyphen, commit 5684c0f51c0b81133db2efbe60a408b4155a3ff5,
 * hyph-utf8/tex/generic/hyph-utf8/patterns/txt/hyph-as.pat.txt).
 *
 * Copyright (C) 2016 Santhosh Thottingal.
 *
 * Licence: This file is available under any of the following licences:
 *
 * MIT (https://opensource.org/licenses/MIT).
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and
 * associated documentation files (the "Software"), to deal in the Software without restriction,
 * including without limitation the rights to use, copy, modify, merge, publish, distribute,
 * sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all copies or
 * substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT
 * NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
 * DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 *
 * LGPL 3 or later (http://www.gnu.org/licenses/lgpl.html).
 *
 * GPL 3 or later (http://www.gnu.org/licenses/gpl.html).
 *
 * The patterns and exceptions are carried unmodified; only their packing into Kotlin strings is
 * new. One Knuth-Liang pattern, or one hyphenated exception word, per line. Generated by
 * tools/generate_hyphenation.py; do not edit by hand.
 */
internal object HyphAs : HyphenPatterns {
    override val minPrefix: Int get() = 1
    override val minSuffix: Int get() = 1

    override val patterns: String get() = P0
    override val exceptions: String get() = ""

    private const val P0 = """
2‍2
1‌1
অ1
আ1
ই1
ঈ1
উ1
ঊ1
ঋ1
ৠ1
ঌ1
ৡ1
এ1
ঐ1
ও1
ঔ1
া1
ি1
ী1
ু1
ূ1
ৃ1
ৄ1
ৢ1
ৣ1
ে1
ৈ1
ো1
ৌ1
2়2
ৗ1
1ক
1খ
1গ
1ঘ
1ঙ
1চ
1ছ
1জ
1ঝ
1ঞ
1ট
1ঠ
1ড
1ড়
1ঢ
1ঢ়
1ণ
1ত
1থ
1দ
1ধ
1ন
1প
1ফ
1ব
1ভ
1ম
1য
1য়
1র
1ল
1শ
1ষ
1স
1হ
ৎ1
2ঃ1
2ং1
2ঁ1
2ঽ1
2্2"""
}
