// Generated by tools/generate_full_width.py from UnicodeData.txt of Unicode 17. Do not hand-edit.
package io.github.yuroyami.kitepdf.epub

/**
 * The full-width form of a character, for `text-transform: full-width` (CSS Text 3, 2.1, #508):
 * the 225 characters that UnicodeData.txt pairs with a full-width form through a `<wide>` or
 * `<narrow>` decomposition, the space aside.
 */
internal object FullWidth {

    /** The full-width form of [cp], or [cp] itself when it has none. */
    fun of(cp: Int): Int {
        if (cp < RUNS[0] || cp > RUNS[RUNS.size - 2]) return cp
        for (r in 0 until RUNS.size / 3) {
            if (cp < RUNS[r * 3]) return cp
            if (cp <= RUNS[r * 3 + 1]) return cp + RUNS[r * 3 + 2]
        }
        return cp
    }

    /** Runs of characters that move by one distance to their full-width forms: the first, the last, the distance. */
    private val RUNS = intArrayOf(
        0x0021, 0x007E, 65248,
        0x00A2, 0x00A3, 65342,
        0x00A5, 0x00A5, 65344,
        0x00A6, 0x00A6, 65342,
        0x00AC, 0x00AC, 65334,
        0x00AF, 0x00AF, 65332,
        0x20A9, 0x20A9, 57149,
        0x2985, 0x2986, 54746,
        0xFF61, 0xFF61, -53087,
        0xFF62, 0xFF63, -53078,
        0xFF64, 0xFF64, -53091,
        0xFF65, 0xFF65, -52842,
        0xFF66, 0xFF66, -52852,
        0xFF67, 0xFF67, -52934,
        0xFF68, 0xFF68, -52933,
        0xFF69, 0xFF69, -52932,
        0xFF6A, 0xFF6A, -52931,
        0xFF6B, 0xFF6B, -52930,
        0xFF6C, 0xFF6C, -52873,
        0xFF6D, 0xFF6D, -52872,
        0xFF6E, 0xFF6E, -52871,
        0xFF6F, 0xFF6F, -52908,
        0xFF70, 0xFF70, -52852,
        0xFF71, 0xFF71, -52943,
        0xFF72, 0xFF72, -52942,
        0xFF73, 0xFF73, -52941,
        0xFF74, 0xFF74, -52940,
        0xFF75, 0xFF76, -52939,
        0xFF77, 0xFF77, -52938,
        0xFF78, 0xFF78, -52937,
        0xFF79, 0xFF79, -52936,
        0xFF7A, 0xFF7A, -52935,
        0xFF7B, 0xFF7B, -52934,
        0xFF7C, 0xFF7C, -52933,
        0xFF7D, 0xFF7D, -52932,
        0xFF7E, 0xFF7E, -52931,
        0xFF7F, 0xFF7F, -52930,
        0xFF80, 0xFF80, -52929,
        0xFF81, 0xFF81, -52928,
        0xFF82, 0xFF82, -52926,
        0xFF83, 0xFF83, -52925,
        0xFF84, 0xFF84, -52924,
        0xFF85, 0xFF8A, -52923,
        0xFF8B, 0xFF8B, -52921,
        0xFF8C, 0xFF8C, -52919,
        0xFF8D, 0xFF8D, -52917,
        0xFF8E, 0xFF8E, -52915,
        0xFF8F, 0xFF93, -52913,
        0xFF94, 0xFF94, -52912,
        0xFF95, 0xFF95, -52911,
        0xFF96, 0xFF9B, -52910,
        0xFF9C, 0xFF9C, -52909,
        0xFF9D, 0xFF9D, -52906,
        0xFF9E, 0xFF9F, -52997,
        0xFFA0, 0xFFA0, -52796,
        0xFFA1, 0xFFBE, -52848,
        0xFFC2, 0xFFC7, -52851,
        0xFFCA, 0xFFCF, -52853,
        0xFFD2, 0xFFD7, -52855,
        0xFFDA, 0xFFDC, -52857,
        0xFFE8, 0xFFE8, -56038,
        0xFFE9, 0xFFEC, -56921,
        0xFFED, 0xFFED, -55885,
        0xFFEE, 0xFFEE, -55843,
    )
}
