package io.github.yuroyami.kitepdf.core.font

/**
 * The four simple-font encodings PDF defines, as tables indexed by byte code.
 *
 * [pdfDocToUnicode] maps a PDFDocEncoding byte to a Unicode codepoint (0 where
 * the code is undefined). The other three map a byte to a PostScript glyph
 * name (null where undefined), which is what a simple font's `/Encoding`
 * selects glyphs by.
 *
 * ## Where these values come from
 *
 * ISO 32000-1, Annex D defines all four. They are reproducible from public,
 * freely usable data, and the test suite checks the reproduction rules rather
 * than trusting the numbers:
 *
 *  - **WinAnsiEncoding** is Windows code page 1252, with three rules from
 *    Annex D: code 240 (0xA0) shows as `space`, 255 (0xAD) as `hyphen`, and
 *    every code above 040 (octal) that the page leaves unused shows as
 *    `bullet`.
 *  - **MacRomanEncoding** is Mac OS Roman *for Latin text*, so the codes whose
 *    Mac OS glyph falls outside that repertoire (the mathematical operators,
 *    Greek letters, the lozenge and the private-use logo) are undefined here.
 *    Code 312 (0xCA) shows as `space`, and 333 (0xDB) keeps `currency`, the
 *    assignment Mac OS used before 8.5 replaced it with the Euro.
 *  - **StandardEncoding** is Adobe's StandardEncoding for Type 1 fonts. It
 *    matches ASCII across 040 to 176 (octal) except that 047 is `quoteright`
 *    and 140 is `quoteleft`.
 *  - **PDFDocEncoding** is Latin-1, with the accent block at 030 to 037
 *    (octal), the typographic set at 200 to 237, the Euro at 240 (0xA0)
 *    instead of a no-break space, and 177 (DEL) and 255 (soft hyphen) left
 *    undefined.
 *
 * Glyph names follow the Adobe Glyph List (see [GlyphList]).
 */
public object Encodings {

    /** PDFDocEncoding byte to Unicode codepoint; 0 where the code is undefined. */
    public val pdfDocToUnicode: IntArray = intArrayOf(
        0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07,
        0x08, 0x09, 0x0a, 0x0b, 0x0c, 0x0d, 0x0e, 0x0f,
        0x10, 0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17,
        0x02d8, 0x02c7, 0x02c6, 0x02d9, 0x02dd, 0x02db, 0x02da, 0x02dc,
        0x20, 0x21, 0x22, 0x23, 0x24, 0x25, 0x26, 0x27,
        0x28, 0x29, 0x2a, 0x2b, 0x2c, 0x2d, 0x2e, 0x2f,
        0x30, 0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37,
        0x38, 0x39, 0x3a, 0x3b, 0x3c, 0x3d, 0x3e, 0x3f,
        0x40, 0x41, 0x42, 0x43, 0x44, 0x45, 0x46, 0x47,
        0x48, 0x49, 0x4a, 0x4b, 0x4c, 0x4d, 0x4e, 0x4f,
        0x50, 0x51, 0x52, 0x53, 0x54, 0x55, 0x56, 0x57,
        0x58, 0x59, 0x5a, 0x5b, 0x5c, 0x5d, 0x5e, 0x5f,
        0x60, 0x61, 0x62, 0x63, 0x64, 0x65, 0x66, 0x67,
        0x68, 0x69, 0x6a, 0x6b, 0x6c, 0x6d, 0x6e, 0x6f,
        0x70, 0x71, 0x72, 0x73, 0x74, 0x75, 0x76, 0x77,
        0x78, 0x79, 0x7a, 0x7b, 0x7c, 0x7d, 0x7e, 0x00,
        0x2022, 0x2020, 0x2021, 0x2026, 0x2014, 0x2013, 0x0192, 0x2044,
        0x2039, 0x203a, 0x2212, 0x2030, 0x201e, 0x201c, 0x201d, 0x2018,
        0x2019, 0x201a, 0x2122, 0xfb01, 0xfb02, 0x0141, 0x0152, 0x0160,
        0x0178, 0x017d, 0x0131, 0x0142, 0x0153, 0x0161, 0x017e, 0x00,
        0x20ac, 0xa1, 0xa2, 0xa3, 0xa4, 0xa5, 0xa6, 0xa7,
        0xa8, 0xa9, 0xaa, 0xab, 0xac, 0x00, 0xae, 0xaf,
        0xb0, 0xb1, 0xb2, 0xb3, 0xb4, 0xb5, 0xb6, 0xb7,
        0xb8, 0xb9, 0xba, 0xbb, 0xbc, 0xbd, 0xbe, 0xbf,
        0xc0, 0xc1, 0xc2, 0xc3, 0xc4, 0xc5, 0xc6, 0xc7,
        0xc8, 0xc9, 0xca, 0xcb, 0xcc, 0xcd, 0xce, 0xcf,
        0xd0, 0xd1, 0xd2, 0xd3, 0xd4, 0xd5, 0xd6, 0xd7,
        0xd8, 0xd9, 0xda, 0xdb, 0xdc, 0xdd, 0xde, 0xdf,
        0xe0, 0xe1, 0xe2, 0xe3, 0xe4, 0xe5, 0xe6, 0xe7,
        0xe8, 0xe9, 0xea, 0xeb, 0xec, 0xed, 0xee, 0xef,
        0xf0, 0xf1, 0xf2, 0xf3, 0xf4, 0xf5, 0xf6, 0xf7,
        0xf8, 0xf9, 0xfa, 0xfb, 0xfc, 0xfd, 0xfe, 0xff,
    )

    /** Adobe StandardEncoding: byte to glyph name, null where undefined. */
    public val standardEncoding: Array<String?> = arrayOf(
        null, null, null, null,
        null, null, null, null,
        null, null, null, null,
        null, null, null, null,
        null, null, null, null,
        null, null, null, null,
        null, null, null, null,
        null, null, null, null,
        "space", "exclam", "quotedbl", "numbersign",
        "dollar", "percent", "ampersand", "quoteright",
        "parenleft", "parenright", "asterisk", "plus",
        "comma", "hyphen", "period", "slash",
        "zero", "one", "two", "three",
        "four", "five", "six", "seven",
        "eight", "nine", "colon", "semicolon",
        "less", "equal", "greater", "question",
        "at", "A", "B", "C",
        "D", "E", "F", "G",
        "H", "I", "J", "K",
        "L", "M", "N", "O",
        "P", "Q", "R", "S",
        "T", "U", "V", "W",
        "X", "Y", "Z", "bracketleft",
        "backslash", "bracketright", "asciicircum", "underscore",
        "quoteleft", "a", "b", "c",
        "d", "e", "f", "g",
        "h", "i", "j", "k",
        "l", "m", "n", "o",
        "p", "q", "r", "s",
        "t", "u", "v", "w",
        "x", "y", "z", "braceleft",
        "bar", "braceright", "asciitilde", null,
        null, null, null, null,
        null, null, null, null,
        null, null, null, null,
        null, null, null, null,
        null, null, null, null,
        null, null, null, null,
        null, null, null, null,
        null, null, null, null,
        null, "exclamdown", "cent", "sterling",
        "fraction", "yen", "florin", "section",
        "currency", "quotesingle", "quotedblleft", "guillemotleft",
        "guilsinglleft", "guilsinglright", "fi", "fl",
        null, "endash", "dagger", "daggerdbl",
        "periodcentered", null, "paragraph", "bullet",
        "quotesinglbase", "quotedblbase", "quotedblright", "guillemotright",
        "ellipsis", "perthousand", null, "questiondown",
        null, "grave", "acute", "circumflex",
        "tilde", "macron", "breve", "dotaccent",
        "dieresis", null, "ring", "cedilla",
        null, "hungarumlaut", "ogonek", "caron",
        "emdash", null, null, null,
        null, null, null, null,
        null, null, null, null,
        null, null, null, null,
        null, "AE", null, "ordfeminine",
        null, null, null, null,
        "Lslash", "Oslash", "OE", "ordmasculine",
        null, null, null, null,
        null, "ae", null, null,
        null, "dotlessi", null, null,
        "lslash", "oslash", "oe", "germandbls",
        null, null, null, null,
    )

    /** MacRomanEncoding: byte to glyph name, null where undefined. */
    public val macRomanEncoding: Array<String?> = arrayOf(
        null, null, null, null,
        null, null, null, null,
        null, null, null, null,
        null, null, null, null,
        null, null, null, null,
        null, null, null, null,
        null, null, null, null,
        null, null, null, null,
        "space", "exclam", "quotedbl", "numbersign",
        "dollar", "percent", "ampersand", "quotesingle",
        "parenleft", "parenright", "asterisk", "plus",
        "comma", "hyphen", "period", "slash",
        "zero", "one", "two", "three",
        "four", "five", "six", "seven",
        "eight", "nine", "colon", "semicolon",
        "less", "equal", "greater", "question",
        "at", "A", "B", "C",
        "D", "E", "F", "G",
        "H", "I", "J", "K",
        "L", "M", "N", "O",
        "P", "Q", "R", "S",
        "T", "U", "V", "W",
        "X", "Y", "Z", "bracketleft",
        "backslash", "bracketright", "asciicircum", "underscore",
        "grave", "a", "b", "c",
        "d", "e", "f", "g",
        "h", "i", "j", "k",
        "l", "m", "n", "o",
        "p", "q", "r", "s",
        "t", "u", "v", "w",
        "x", "y", "z", "braceleft",
        "bar", "braceright", "asciitilde", null,
        "Adieresis", "Aring", "Ccedilla", "Eacute",
        "Ntilde", "Odieresis", "Udieresis", "aacute",
        "agrave", "acircumflex", "adieresis", "atilde",
        "aring", "ccedilla", "eacute", "egrave",
        "ecircumflex", "edieresis", "iacute", "igrave",
        "icircumflex", "idieresis", "ntilde", "oacute",
        "ograve", "ocircumflex", "odieresis", "otilde",
        "uacute", "ugrave", "ucircumflex", "udieresis",
        "dagger", "degree", "cent", "sterling",
        "section", "bullet", "paragraph", "germandbls",
        "registered", "copyright", "trademark", "acute",
        "dieresis", null, "AE", "Oslash",
        null, "plusminus", null, null,
        "yen", "mu", null, null,
        null, null, null, "ordfeminine",
        "ordmasculine", null, "ae", "oslash",
        "questiondown", "exclamdown", "logicalnot", null,
        "florin", null, null, "guillemotleft",
        "guillemotright", "ellipsis", "space", "Agrave",
        "Atilde", "Otilde", "OE", "oe",
        "endash", "emdash", "quotedblleft", "quotedblright",
        "quoteleft", "quoteright", "divide", null,
        "ydieresis", "Ydieresis", "fraction", "currency",
        "guilsinglleft", "guilsinglright", "fi", "fl",
        "daggerdbl", "periodcentered", "quotesinglbase", "quotedblbase",
        "perthousand", "Acircumflex", "Ecircumflex", "Aacute",
        "Edieresis", "Egrave", "Iacute", "Icircumflex",
        "Idieresis", "Igrave", "Oacute", "Ocircumflex",
        null, "Ograve", "Uacute", "Ucircumflex",
        "Ugrave", "dotlessi", "circumflex", "tilde",
        "macron", "breve", "dotaccent", "ring",
        "cedilla", "hungarumlaut", "ogonek", "caron",
    )

    /** WinAnsiEncoding: byte to glyph name, null where undefined. */
    public val winAnsiEncoding: Array<String?> = arrayOf(
        null, null, null, null,
        null, null, null, null,
        null, null, null, null,
        null, null, null, null,
        null, null, null, null,
        null, null, null, null,
        null, null, null, null,
        null, null, null, null,
        "space", "exclam", "quotedbl", "numbersign",
        "dollar", "percent", "ampersand", "quotesingle",
        "parenleft", "parenright", "asterisk", "plus",
        "comma", "hyphen", "period", "slash",
        "zero", "one", "two", "three",
        "four", "five", "six", "seven",
        "eight", "nine", "colon", "semicolon",
        "less", "equal", "greater", "question",
        "at", "A", "B", "C",
        "D", "E", "F", "G",
        "H", "I", "J", "K",
        "L", "M", "N", "O",
        "P", "Q", "R", "S",
        "T", "U", "V", "W",
        "X", "Y", "Z", "bracketleft",
        "backslash", "bracketright", "asciicircum", "underscore",
        "grave", "a", "b", "c",
        "d", "e", "f", "g",
        "h", "i", "j", "k",
        "l", "m", "n", "o",
        "p", "q", "r", "s",
        "t", "u", "v", "w",
        "x", "y", "z", "braceleft",
        "bar", "braceright", "asciitilde", "bullet",
        "Euro", "bullet", "quotesinglbase", "florin",
        "quotedblbase", "ellipsis", "dagger", "daggerdbl",
        "circumflex", "perthousand", "Scaron", "guilsinglleft",
        "OE", "bullet", "Zcaron", "bullet",
        "bullet", "quoteleft", "quoteright", "quotedblleft",
        "quotedblright", "bullet", "endash", "emdash",
        "tilde", "trademark", "scaron", "guilsinglright",
        "oe", "bullet", "zcaron", "Ydieresis",
        "space", "exclamdown", "cent", "sterling",
        "currency", "yen", "brokenbar", "section",
        "dieresis", "copyright", "ordfeminine", "guillemotleft",
        "logicalnot", "hyphen", "registered", "macron",
        "degree", "plusminus", "twosuperior", "threesuperior",
        "acute", "mu", "paragraph", "periodcentered",
        "cedilla", "onesuperior", "ordmasculine", "guillemotright",
        "onequarter", "onehalf", "threequarters", "questiondown",
        "Agrave", "Aacute", "Acircumflex", "Atilde",
        "Adieresis", "Aring", "AE", "Ccedilla",
        "Egrave", "Eacute", "Ecircumflex", "Edieresis",
        "Igrave", "Iacute", "Icircumflex", "Idieresis",
        "Eth", "Ntilde", "Ograve", "Oacute",
        "Ocircumflex", "Otilde", "Odieresis", "multiply",
        "Oslash", "Ugrave", "Uacute", "Ucircumflex",
        "Udieresis", "Yacute", "Thorn", "germandbls",
        "agrave", "aacute", "acircumflex", "atilde",
        "adieresis", "aring", "ae", "ccedilla",
        "egrave", "eacute", "ecircumflex", "edieresis",
        "igrave", "iacute", "icircumflex", "idieresis",
        "eth", "ntilde", "ograve", "oacute",
        "ocircumflex", "otilde", "odieresis", "divide",
        "oslash", "ugrave", "uacute", "ucircumflex",
        "udieresis", "yacute", "thorn", "ydieresis",
    )
}
