#!/usr/bin/env python3
"""Writes Standard14FontData.kt: the URW base 35 CFF programs that draw the standard 14 fonts.

The fonts come from the resources/fonts/urw folder of a MuPDF checkout, under the
SIL Open Font License 1.1. Each program is stored as raw DEFLATE, then Base64, in
chunks that fit a JVM string constant.

    python3 tools/generate_standard14_fonts.py [path/to/mupdf/resources/fonts/urw]
"""

import base64
import os
import sys
import zlib

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SOURCE = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, "mupdf-master", "resources", "fonts", "urw")
TARGET = os.path.join(ROOT, "kitepdf-core", "src", "commonMain", "kotlin", "io", "github", "yuroyami",
                      "kitepdf", "core", "font", "Standard14FontData.kt")
FILES = [
    "NimbusSans-Regular", "NimbusSans-Bold", "NimbusSans-Italic", "NimbusSans-BoldItalic",
    "NimbusRoman-Regular", "NimbusRoman-Bold", "NimbusRoman-Italic", "NimbusRoman-BoldItalic",
    "NimbusMonoPS-Regular", "NimbusMonoPS-Bold", "NimbusMonoPS-Italic", "NimbusMonoPS-BoldItalic",
    "StandardSymbolsPS", "Dingbats",
]
CHUNK = 60_000


def deflate_raw(data):
    compressor = zlib.compressobj(9, zlib.DEFLATED, -15)
    return compressor.compress(data) + compressor.flush()


def function_name(file):
    parts = file.replace("-", " ").split()
    name = "".join(p[:1].upper() + p[1:] for p in parts)
    return name[:1].lower() + name[1:]


def main():
    license_text = open(os.path.join(SOURCE, "OFL.txt"), encoding="utf-8").read().strip()
    assert "*/" not in license_text
    out = []
    out.append("// Generated by tools/generate_standard14_fonts.py from MuPDF's resources/fonts/urw. Do not hand-edit.")
    out.append("package io.github.yuroyami.kitepdf.core.font")
    out.append("")
    out.append("/*")
    for line in license_text.splitlines():
        out.append((" * " + line).rstrip())
    out.append(" */")
    out.append("")
    out.append("/**")
    out.append(" * The CFF programs of the URW base 35 fonts that draw the standard 14 fonts, by file")
    out.append(" * name (see [Standard14Fonts]). Each program is raw DEFLATE, then Base64, in chunks")
    out.append(" * that fit a JVM string constant.")
    out.append(" */")
    out.append("internal object Standard14FontData {")
    out.append("")
    out.append("    fun chunks(file: String): Array<String>? = when (file) {")
    for file in FILES:
        out.append(f'        "{file}" -> {function_name(file)}()')
    out.append("        else -> null")
    out.append("    }")
    total_raw = total_b64 = 0
    for file in FILES:
        data = open(os.path.join(SOURCE, file + ".cff"), "rb").read()
        encoded = base64.b64encode(deflate_raw(data)).decode("ascii")
        total_raw += len(data)
        total_b64 += len(encoded)
        out.append("")
        out.append(f"    private fun {function_name(file)}(): Array<String> = arrayOf(")
        for i in range(0, len(encoded), CHUNK):
            out.append(f'        "{encoded[i:i + CHUNK]}",')
        out.append("    )")
    out.append("}")
    with open(TARGET, "w", encoding="utf-8") as f:
        f.write("\n".join(out) + "\n")
    print(f"wrote {TARGET}: {len(FILES)} fonts, {total_raw} bytes of CFF, {total_b64} characters of Base64")


if __name__ == "__main__":
    main()
