#!/usr/bin/env python3
"""Writes FullWidth.kt, the characters that `text-transform: full-width` changes (#508).

    mkdir -p ~/.cache/kitepdf/ucd-17 && cd ~/.cache/kitepdf/ucd-17
    curl -O https://www.unicode.org/Public/17.0.0/ucd/UnicodeData.txt
    python3 tools/generate_full_width.py [folder]

CSS Text 3 (2.1) puts each character in its full-width form when it has one. UnicodeData.txt
gives the pairs as decompositions: a full-width character decomposes `<wide>` to its ordinary
form, and a half-width one `<narrow>` to its full form. The space is left out, so it still
collapses and still lets a line wrap.
"""

import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TARGET = os.path.join(ROOT, "kitepdf-epub", "src", "commonMain", "kotlin", "io", "github", "yuroyami",
                      "kitepdf", "epub", "FullWidth.kt")


def pairs(folder):
    """Each character that has a full-width form, to that form."""
    wide, narrow = {}, {}
    with open(os.path.join(folder, "UnicodeData.txt"), encoding="utf-8") as f:
        for line in f:
            fields = line.split(";")
            cp, decomposition = int(fields[0], 16), fields[5].split()
            if len(decomposition) != 2:
                continue
            if decomposition[0] == "<wide>":
                wide.setdefault(int(decomposition[1], 16), cp)
            elif decomposition[0] == "<narrow>":
                narrow[cp] = int(decomposition[1], 16)
    out = dict(wide)
    for cp, full in narrow.items():
        out.setdefault(cp, full)
    out.pop(0x20, None)
    return out


def runs(mapping):
    """Runs of consecutive characters that move by the same distance: first, last, distance."""
    out = []
    for cp in sorted(mapping):
        d = mapping[cp] - cp
        if out and out[-1][1] == cp - 1 and out[-1][2] == d:
            out[-1][1] = cp
        else:
            out.append([cp, cp, d])
    return out


def main():
    folder = sys.argv[1] if len(sys.argv) > 1 else os.path.expanduser("~/.cache/kitepdf/ucd-17")
    mapping = pairs(folder)
    table = runs(mapping)
    rows = "\n".join(f"        0x{a:04X}, 0x{b:04X}, {d}," for a, b, d in table)
    with open(TARGET, "w", encoding="utf-8") as f:
        f.write(f"""// Generated by tools/generate_full_width.py from UnicodeData.txt of Unicode 17. Do not hand-edit.
package io.github.yuroyami.kitepdf.epub

/**
 * The full-width form of a character, for `text-transform: full-width` (CSS Text 3, 2.1, #508):
 * the {len(mapping)} characters that UnicodeData.txt pairs with a full-width form through a `<wide>` or
 * `<narrow>` decomposition, the space aside.
 */
internal object FullWidth {{

    /** The full-width form of [cp], or [cp] itself when it has none. */
    fun of(cp: Int): Int {{
        if (cp < RUNS[0] || cp > RUNS[RUNS.size - 2]) return cp
        for (r in 0 until RUNS.size / 3) {{
            if (cp < RUNS[r * 3]) return cp
            if (cp <= RUNS[r * 3 + 1]) return cp + RUNS[r * 3 + 2]
        }}
        return cp
    }}

    /** Runs of characters that move by one distance to their full-width forms: the first, the last, the distance. */
    private val RUNS = intArrayOf(
{rows}
    )
}}
""")
    print(f"wrote {len(mapping)} characters in {len(table)} runs to {os.path.relpath(TARGET, ROOT)}")


if __name__ == "__main__":
    main()
