#!/usr/bin/env python3
"""Writes ZapfDingbatsGlyphList.kt from Adobe's zapfdingbats.txt (AGL project, BSD-3-Clause).

    curl -s -o zapfdingbats.txt https://raw.githubusercontent.com/adobe-type-tools/agl-aglfn/master/zapfdingbats.txt
    python3 tools/generate_zapfdingbats_glyph_list.py zapfdingbats.txt
"""

import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TARGET = os.path.join(ROOT, "kitepdf-core", "src", "commonMain", "kotlin", "io", "github", "yuroyami",
                      "kitepdf", "core", "font", "ZapfDingbatsGlyphList.kt")


def main():
    lines = open(sys.argv[1], encoding="utf-8").read().splitlines()
    header = [l[2:] if l.startswith("# ") else l[1:] for l in lines if l.startswith("#")]
    pairs = [l.split(";") for l in lines if l and not l.startswith("#")]
    assert all(len(p) == 2 for p in pairs), "unexpected line"
    packed = "".join(f"{name}={code};" for name, code in pairs)
    out = ["// Generated by tools/generate_zapfdingbats_glyph_list.py from Adobe's zapfdingbats.txt. Do not hand-edit.",
           "package io.github.yuroyami.kitepdf.core.font", "", "/*"]
    out += [(" * " + l).rstrip() for l in header]
    out += [" */", "",
            "/**",
            " * The Unicode value of each glyph name of the ZapfDingbats font, `a1` to `a191` and",
            " * `a201` to `a206`. The Adobe Glyph List does not hold these names, and the AGL",
            " * specification says to use this list for ZapfDingbats alone (#305).",
            " */",
            "internal object ZapfDingbatsGlyphList {",
            "",
            "    private val map: Map<String, Int> by lazy {",
            '        PACKED.split(\';\').filter { it.isNotEmpty() }.associate { entry ->',
            "            val eq = entry.indexOf('=')",
            "            entry.substring(0, eq) to entry.substring(eq + 1).toInt(16)",
            "        }",
            "    }",
            "",
            "    fun unicodeFor(glyphName: String): Int? = map[glyphName]",
            ""]
    chunks = [packed[i:i + 100] for i in range(0, len(packed), 100)]
    out.append("    private const val PACKED: String = " + " +\n        ".join(f'"{c}"' for c in chunks))
    out.append("}")
    with open(TARGET, "w", encoding="utf-8") as f:
        f.write("\n".join(out) + "\n")
    print(f"wrote {TARGET}: {len(pairs)} names")


if __name__ == "__main__":
    main()
