#!/usr/bin/env python3
"""Writes HtmlEntities.kt, HTML's named character references, from Python's copy of the table (#570).

    python3 tools/generate_html_entities.py [target file]

The table is the one of HTML, 13.5, which WHATWG publishes as entities.json and keeps static: no
name is added or changed. Python's `html.entities.html5` holds the same table, so this needs no
download. Only the names that end in a semicolon are written, since a name without one is
recognized only in an HTML document's text, by rules a forgiving XML reader does not follow.

The names and their characters go into one string, each name followed by a semicolon, which no
name holds, its characters, and a NUL, which no replacement holds. A Kotlin map of two thousand
pairs would be a static initializer too large for a JVM method, and a string stays well under a
class file's 64 KB constant limit.
"""

import os
import sys
from html.entities import html5

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TARGET = os.path.join(ROOT, "kitepdf-core", "src", "commonMain", "kotlin", "io", "github", "yuroyami",
                      "kitepdf", "core", "xml", "HtmlEntities.kt")


def escape(s):
    out = []
    for c in s:
        cp = ord(c)
        if 0x20 <= cp < 0x7F and c not in '"\\$':
            out.append(c)
        elif cp > 0xFFFF:
            v = cp - 0x10000
            out.append(f"\\u{0xD800 + (v >> 10):04x}\\u{0xDC00 + (v & 0x3FF):04x}")
        else:
            out.append(f"\\u{cp:04x}")
    return "".join(out)


def main():
    target = sys.argv[1] if len(sys.argv) > 1 else TARGET
    names = sorted(k[:-1] for k in html5 if k.endswith(";"))
    assert all(n.isalnum() and n.isascii() for n in names), "a name that is not ASCII letters and digits"
    assert all("\0" not in html5[n + ";"] for n in names), "a replacement that holds a NUL"
    longest = max(len(n) for n in names)
    packed = "".join(n + ";" + html5[n + ";"] + "\0" for n in names)
    assert len(packed.encode("utf-8")) < 60000, "the table no longer fits one class file constant"
    # Lines of about a hundred characters of source, split between entries.
    lines, line = [], ""
    for n in names:
        entry = escape(n + ";" + html5[n + ";"]) + "\\u0000"
        if line and len(line) + len(entry) > 100:
            lines.append(line)
            line = ""
        line += entry
    lines.append(line)
    body = "\n".join(f'        "{l}" +' for l in lines).rstrip(" +")
    with open(target, "w", encoding="utf-8") as f:
        f.write(f"""// Generated by tools/generate_html_entities.py from HTML's named character references. Do not hand-edit.
package io.github.yuroyami.kitepdf.core.xml

/**
 * HTML's named character references that end in a semicolon (HTML, 13.5), {len(names)} names, which
 * hold every entity of the XHTML 1.0 and 1.1 DTDs (#570).
 */
internal object HtmlEntities {{

    /** The length of the longest name, without its `&` and `;`. */
    const val LONGEST: Int = {longest}

    /** The characters that the name stands for, or null when HTML has no such name. Names are case-sensitive. */
    fun lookup(name: String): String? = table[name]

    private val table: Map<String, String> by lazy {{
        val map = HashMap<String, String>({len(names) * 4 // 3})
        var start = 0
        while (start < PACKED.length) {{
            val semicolon = PACKED.indexOf(';', start)
            val end = PACKED.indexOf('\\u0000', semicolon + 1)
            map[PACKED.substring(start, semicolon)] = PACKED.substring(semicolon + 1, end)
            start = end + 1
        }}
        map
    }}

    /** Each name, a semicolon, its characters and a NUL, in the order of the names. */
    private const val PACKED: String =
{body}
}}
""")
    print(f"wrote {len(names)} names to {os.path.relpath(target, ROOT)}")


if __name__ == "__main__":
    main()
