#!/usr/bin/env python3
"""Writes QuoteData.kt, the quotation marks of each language, from CLDR's delimiters (#511).

    python3 tools/generate_quote_tables.py [cache folder]

It downloads the delimiters of every CLDR locale into the cache folder, ~/.cache/kitepdf/cldr-48.2.0
unless one is given, and reads them from there on later runs.

`quotes: auto` takes the marks of the element's content language from CLDR (CSS Generated
Content 3, 2.4). The lookup in QuoteData.kt drops subtags from the end of a language tag until
one is in the table, and ends at English, so the table keeps a locale only where its marks differ
from what that lookup would find without it.
"""

import json
import os
import sys
import urllib.request
from concurrent.futures import ThreadPoolExecutor

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TARGET = os.path.join(ROOT, "kitepdf-epub", "src", "commonMain", "kotlin", "io", "github", "yuroyami",
                      "kitepdf", "epub", "css", "QuoteData.kt")
VERSION = "48.2.0"
BASE = f"https://raw.githubusercontent.com/unicode-org/cldr-json/{VERSION}/cldr-json"
KEYS = ("quotationStart", "quotationEnd", "alternateQuotationStart", "alternateQuotationEnd")


def fetch(url, path):
    if not os.path.exists(path):
        with urllib.request.urlopen(url) as r:
            data = r.read()
        with open(path, "wb") as f:
            f.write(data)
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def main():
    cache = sys.argv[1] if len(sys.argv) > 1 else os.path.expanduser(f"~/.cache/kitepdf/cldr-{VERSION}")
    os.makedirs(cache, exist_ok=True)
    locales = fetch(f"{BASE}/cldr-core/availableLocales.json", os.path.join(cache, "availableLocales.json"))
    locales = locales["availableLocales"]["full"]

    def delimiters(locale):
        doc = fetch(f"{BASE}/cldr-misc-full/main/{locale}/delimiters.json", os.path.join(cache, f"{locale}.json"))
        d = doc["main"][locale]["delimiters"]
        return locale, "".join(d[k] for k in KEYS)

    with ThreadPoolExecutor(16) as pool:
        marks = {loc.lower(): m for loc, m in pool.map(delimiters, locales)}
    assert all(len(m) == 4 for m in marks.values()), "a mark of more than one character"

    default = marks["en"]
    kept = {}
    for tag in sorted(marks, key=lambda t: (t.count("-"), t)):
        if tag == "root" or tag == "en":
            continue
        parts = tag.split("-")
        found = default
        for n in range(len(parts) - 1, 0, -1):
            if "-".join(parts[:n]) in kept:
                found = kept["-".join(parts[:n])]
                break
        if marks[tag] != found:
            kept[tag] = marks[tag]

    def escape(s):
        return "".join(c if 0x20 <= ord(c) < 0x7F and c not in '"\\$' else f"\\u{ord(c):04x}" for c in s)

    rows = "\n".join(f'        "{tag}" to "{escape(m)}",' for tag, m in sorted(kept.items()))
    with open(TARGET, "w", encoding="utf-8") as f:
        f.write(f"""// Generated by tools/generate_quote_tables.py from CLDR {VERSION}. Do not hand-edit.
package io.github.yuroyami.kitepdf.epub.css

/**
 * The quotation marks of each language that `quotes: auto` draws, from the delimiters of CLDR
 * {VERSION} (#511): the opening and closing marks, then the pair for a quotation inside one.
 */
internal object QuoteData {{

    /** English's marks, which a language the table does not hold falls back to. */
    const val DEFAULT: String = "{escape(default)}"

    /** The {len(kept)} locales, lower case, whose marks differ from what [DEFAULT] and their shorter tags give. */
    val MARKS: Map<String, String> = mapOf(
{rows}
    )
}}
""")
    print(f"wrote {len(kept)} of {len(marks)} locales to {os.path.relpath(TARGET, ROOT)}")


if __name__ == "__main__":
    main()
