#!/usr/bin/env python3
"""Writes AdobeCmykTable.kt: PDFium's table for DeviceCMYK to sRGB.

The table comes from core/fxge/dib/cfx_cmyk_to_srgb.cpp of PDFium, under the
BSD license of PDFium (original code copyright 2014 Foxit Software Inc.):

    curl -s "https://pdfium.googlesource.com/pdfium/+/refs/heads/main/core/fxge/dib/cfx_cmyk_to_srgb.cpp?format=TEXT" \
      | base64 -d > cfx_cmyk_to_srgb.cpp
    python3 tools/generate_adobe_cmyk_table.py cfx_cmyk_to_srgb.cpp
"""

import base64
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TARGET = os.path.join(ROOT, "kitepdf-core", "src", "commonMain", "kotlin", "io", "github", "yuroyami",
                      "kitepdf", "core", "render", "AdobeCmykTable.kt")


def main():
    source = open(sys.argv[1], encoding="utf-8").read()
    start = source.index("kCMYK = {{")
    end = source.index("}};", start)
    triples = re.findall(r"\{\s*(\d+),\s*(\d+),\s*(\d+)\s*\}", source[start:end])
    assert len(triples) == 9 ** 4, len(triples)
    data = bytes(int(v) for t in triples for v in t)
    encoded = base64.b64encode(data).decode("ascii")
    lines = [encoded[i:i + 100] for i in range(0, len(encoded), 100)]
    out = [
        "// Generated by tools/generate_adobe_cmyk_table.py from PDFium's core/fxge/dib/cfx_cmyk_to_srgb.cpp. Do not hand-edit.",
        "package io.github.yuroyami.kitepdf.core.render",
        "",
        "/*",
        " * Copyright 2019 The PDFium Authors. Original code copyright 2014 Foxit Software Inc.",
        " * Use of this data is governed by the BSD-style license of PDFium:",
        " * https://pdfium.googlesource.com/pdfium/+/refs/heads/main/LICENSE",
        " */",
        "",
        "/**",
        " * The sRGB colour of each point of a 9 by 9 by 9 by 9 grid over C, M, Y and K, as three",
        " * bytes, indexed by 729 C + 81 M + 9 Y + K. See [AdobeCmyk].",
        " */",
        "internal object AdobeCmykTable {",
        "    val base64: String = " + " +\n        ".join(f'"{line}"' for line in lines),
        "}",
    ]
    with open(TARGET, "w", encoding="utf-8") as f:
        f.write("\n".join(out) + "\n")
    print(f"wrote {TARGET}: {len(data)} bytes, {len(encoded)} characters")


if __name__ == "__main__":
    main()
